export const GET_SEARCH_DETAILS="GET_SEARCH_DETAILS";

export const GET_MOVİE_SUCCESS ="GET_MOVİE_SUCCESS";

export const ADD_TO_FAVORITES="ADD_TO_FAVORITES";

export const VIEW_DETAILS = "VIEW_DETAILS";